import { getApps, getApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import { getDocs, getFirestore, serverTimestamp, writeBatch } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-firestore.js";
import { resolveShopContext, shopCollection, shopDoc } from "../multi-shop-core.js";

const app=getApps().length?getApp():null;
if(!app) throw new Error('Firebase app not ready');
const auth=getAuth(app), db=getFirestore(app);
const $=s=>document.querySelector(s);
const money=n=>`NT$${Math.max(0,Number(n)||0).toLocaleString('zh-TW')}`;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
let user=null, context=null, rows=[];

function millis(v){if(typeof v?.toMillis==='function')return v.toMillis();if(v?.seconds)return v.seconds*1000;return Date.parse(v||'')||0;}
function date(v){const m=millis(v);return m?new Intl.DateTimeFormat('zh-TW',{dateStyle:'short',timeStyle:'short'}).format(new Date(m)):'—';}
function stateOf(o){return o.reviewStatus||({已確認:'confirmed',已拒絕:'rejected'}[o.status])||'pending';}
function installUI(){
  const section=$('#admin-section-orders'); if(!section||section.dataset.reviewReady)return;
  section.dataset.reviewReady='1';
  section.innerHTML=`
    <div class="flex flex-wrap justify-between items-end gap-3"><div><p class="text-xs text-sky-400 font-bold">ONLINE ORDER REVIEW</p><h2 class="text-xl font-black">線上訂單待審核 <span id="jerryPendingCount" class="text-amber-400"></span></h2><p class="text-xs text-slate-500 mt-1">前台送出只會進這裡；按「確認」後才建立正式訂單。</p></div><div class="flex gap-2"><input id="jerryReviewSearch" placeholder="搜尋姓名、電話、車款" class="bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-xs"/><button id="jerryReviewRefresh" class="bg-slate-800 border border-slate-700 px-3 py-2 rounded-xl text-xs">重新整理</button></div></div>
    <div class="grid grid-cols-3 gap-3"><div class="glass-card rounded-2xl p-4"><small class="text-slate-500">待審核</small><b id="statPending" class="block text-2xl text-amber-400">0</b></div><div class="glass-card rounded-2xl p-4"><small class="text-slate-500">已確認</small><b id="statConfirmed" class="block text-2xl text-emerald-400">0</b></div><div class="glass-card rounded-2xl p-4"><small class="text-slate-500">已拒絕</small><b id="statRejected" class="block text-2xl text-rose-400">0</b></div></div>
    <div class="glass-card rounded-2xl overflow-x-auto"><table class="w-full text-left text-xs min-w-[1080px]"><thead><tr class="border-b border-slate-800 text-slate-500"><th class="p-3">訂單編號</th><th class="p-3">客戶</th><th class="p-3">車款／規格</th><th class="p-3">配送／付款</th><th class="p-3">金額</th><th class="p-3">狀態</th><th class="p-3">操作</th><th class="p-3">時間</th></tr></thead><tbody id="jerryReviewBody" class="divide-y divide-slate-800/80"></tbody></table></div>`;
  $('#jerryReviewSearch')?.addEventListener('input',render);
  $('#jerryReviewRefresh')?.addEventListener('click',load);
  const tab=document.querySelector('[data-admin-tab="orders"]'); if(tab)tab.innerHTML='<i class="fa-solid fa-file-invoice mr-1"></i>線上訂單 <span id="jerryTabBadge"></span>';
}
function normalize(doc){const d=doc.data();return{id:doc.id,raw:d,orderNo:d.orderNo||d.orderId||doc.id,customerName:d.customerName||'未命名',phone:d.phone||'—',address:d.address||'—',model:d.model||'—',variant:d.vehicleVariant||d.variant||'',delivery:d.deliveryMode||d.deliveryMethod||'—',payment:d.paymentMethod||'—',price:Number(d.price)||0,status:d.status||'待審核',reviewStatus:d.reviewStatus||'pending',createdAt:d.createdAt||''};}
async function load(){if(!context)return;const body=$('#jerryReviewBody');if(body)body.innerHTML='<tr><td colspan="8" class="p-5 text-center text-slate-500">讀取線上訂單中…</td></tr>';try{const snap=await getDocs(shopCollection(db,context,'onlineOrders'));rows=snap.docs.map(normalize).sort((a,b)=>millis(b.createdAt)-millis(a.createdAt));render();}catch(e){console.error(e);if(body)body.innerHTML=`<tr><td colspan="8" class="p-5 text-center text-rose-400">載入失敗：${esc(e.message||'請檢查權限')}</td></tr>`;}}
function render(){const body=$('#jerryReviewBody');if(!body)return;const key=($('#jerryReviewSearch')?.value||'').trim().toLowerCase();const filtered=rows.filter(o=>[o.orderNo,o.customerName,o.phone,o.model,o.variant].join(' ').toLowerCase().includes(key));const counts={pending:0,confirmed:0,rejected:0};rows.forEach(o=>{const s=stateOf(o);if(counts[s]!==undefined)counts[s]++;});$('#statPending').textContent=counts.pending;$('#statConfirmed').textContent=counts.confirmed;$('#statRejected').textContent=counts.rejected;$('#jerryPendingCount').textContent=counts.pending?`(${counts.pending})`:'';const badge=$('#jerryTabBadge');if(badge)badge.textContent=counts.pending?`(${counts.pending})`:'';if(!filtered.length){body.innerHTML='<tr><td colspan="8" class="p-5 text-center text-slate-500">目前沒有線上訂單</td></tr>';return;}body.innerHTML=filtered.map(o=>{const s=stateOf(o),label=s==='confirmed'?'已確認':s==='rejected'?'已拒絕':'待審核',color=s==='confirmed'?'text-emerald-400':s==='rejected'?'text-rose-400':'text-amber-400';return `<tr><td class="p-3 font-bold text-sky-400">${esc(o.orderNo)}</td><td class="p-3"><strong class="block text-white">${esc(o.customerName)}</strong><small class="text-slate-500">${esc(o.phone)}</small></td><td class="p-3"><strong class="block">${esc(o.model)}</strong><small class="text-slate-500">${esc(o.variant)}</small></td><td class="p-3"><span class="block">${esc(o.delivery)}</span><small class="text-slate-500">${esc(o.payment)}</small></td><td class="p-3 font-bold">${money(o.price)}</td><td class="p-3 font-bold ${color}">${label}</td><td class="p-3">${s==='pending'?`<div class="flex gap-2"><button class="confirm-online bg-emerald-500 text-slate-950 font-black px-3 py-2 rounded-lg" data-id="${esc(o.id)}">確認</button><button class="reject-online bg-rose-500 text-white font-black px-3 py-2 rounded-lg" data-id="${esc(o.id)}">拒絕</button></div>`:`<span class="text-slate-500">${s==='confirmed'?'已進正式訂單':'不建立正式訂單'}</span>`}</td><td class="p-3 text-slate-500">${date(o.createdAt)}</td></tr>`;}).join('');
  document.querySelectorAll('.confirm-online').forEach(b=>b.addEventListener('click',()=>confirmOrder(b.dataset.id,b)));
  document.querySelectorAll('.reject-online').forEach(b=>b.addEventListener('click',()=>rejectOrder(b.dataset.id,b)));
}
async function confirmOrder(id,button){const o=rows.find(x=>x.id===id);if(!o||stateOf(o)!=='pending')return;if(!confirm(`確認 ${o.customerName} 的訂單？\n確認後才會加入正式訂單管理。`))return;button.disabled=true;try{const batch=writeBatch(db),formal=shopDoc(db,context,'orders',id),online=shopDoc(db,context,'onlineOrders',id),raw=o.raw||{};batch.set(formal,{...raw,orderId:id,orderNo:o.orderNo,shopId:'jerry',source:'official-store',status:'待訂金',reviewStatus:'confirmed',sourceOnlineOrderId:id,approvedAt:serverTimestamp(),approvedBy:user.uid,updatedAt:serverTimestamp()},{merge:true});batch.set(online,{reviewStatus:'confirmed',status:'已確認',formalOrderId:id,approvedAt:serverTimestamp(),approvedBy:user.uid,updatedAt:serverTimestamp()},{merge:true});await batch.commit();await load();}catch(e){console.error(e);alert(`確認失敗：${e.message||'請檢查權限'}`);button.disabled=false;}}
async function rejectOrder(id,button){const o=rows.find(x=>x.id===id);if(!o||stateOf(o)!=='pending')return;if(!confirm(`拒絕 ${o.customerName} 的線上訂單？\n這筆不會加入正式訂單。`))return;button.disabled=true;try{const batch=writeBatch(db);batch.set(shopDoc(db,context,'onlineOrders',id),{reviewStatus:'rejected',status:'已拒絕',rejectedAt:serverTimestamp(),rejectedBy:user.uid,updatedAt:serverTimestamp()},{merge:true});await batch.commit();await load();}catch(e){console.error(e);alert(`拒絕失敗：${e.message||'請檢查權限'}`);button.disabled=false;}}
installUI();
onAuthStateChanged(auth,async u=>{if(!u)return;try{const ctx=await resolveShopContext(db,u);if(ctx.shopId!=='jerry')return;user=u;context=ctx;installUI();await load();}catch(e){console.error('Jerry online review',e);}});
